Add Content Warning to stories
my-covid-story/www pull request #120
Opened 2021-04-27 02:58 UTC by silent1mezzo

2021-04-27 03:29 UTC, davesteinberg commented
The latest design has the content warning label replacing the category label in the story cards on the feed, in order to keep the size constant (Figma is up to date). Also, there's an existing `Label` common component that you can reuse for it, you just need to pass in `color` and `background` props (it automatically uses `color` for `borderColor`, as well).

2021-04-27 23:53 UTC, JamiesonRoberts requested changes

2021-04-27 23:53 UTC, JamiesonRoberts commented on components/common/Warnings.tsx
> +export function ContentWarningBox({ ...props }) {
Type on this please! BoxProps should be the correct one

2021-04-27 23:55 UTC, mwickett approved these changes
Once that type issue is resolved, LGTM.

2021-04-28 01:50 UTC, JamiesonRoberts approved these changes

2021-04-28 01:51 UTC, JamiesonRoberts commented
LGTM! 🚀

2021-04-28 01:56 UTC, merged