Update Ontarian -> Canadian
my-covid-story/www pull request #181
Opened 2021-05-28 19:07 UTC by silent1mezzo

fixes #180

2021-05-28 19:10 UTC, silent1mezzo commented
#### 📝Changed routes:


| [**/about**](https://www-1p9yfye7j-my-covid-story.vercel.app/about) | [**/faq**](https://www-1p9yfye7j-my-covid-story.vercel.app/faq) |
|:-:|:-:|
|<a href="https://www-1p9yfye7j-my-covid-story.vercel.app/about"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/EuwWQWScGHsevisPVhkGHDUfORUxMhuHLUNYTFuAJ8EpA9D100xfxbxshchIEAgSt4HFgZjZi-DB7OBhG27Dvw.png&w=600" alt="Screenshot of /about" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/HXW-OAqIuoyA4p_Vz5MyNehAVRZ0XqW3NQMpMT6x_FdJsAuey0hHTx5Kj_iM-QAQuEmdTbwu3yJL4cKT9hgp3g.png">(view full size)</a> |<a href="https://www-1p9yfye7j-my-covid-story.vercel.app/faq"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/blQ-MSwEV-3Uhax6fdFWNH8OV7gzaFlSFIO8qfk-aNbko_aJlnpVtVTltEMhLIGDHA3ngKk_fR4fU8sfsh6lGg.png&w=600" alt="Screenshot of /faq" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/1F0IWPe7iLKb5v48BF7GmmF8xMjrjwNHyhs0qNb6oAtDD2rRMR7HmaASokUaGs_Hmgy6LeUKsg4UQH9omepXjg.png">(view full size)</a> |



| [**/new**](https://www-1p9yfye7j-my-covid-story.vercel.app/new) |
|:-:|
|<a href="https://www-1p9yfye7j-my-covid-story.vercel.app/new"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/ZnPcAXXjuLINCv5qc3USDFeGWDlICDMOtQqM3XAw-6QRVpVMG-sfiv2ajqutWLJ5s-I3ElTuz4x4_p8zNWDebQ.png&w=600" alt="Screenshot of /new" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/uKNBMv4yhjyk7MTN0MVdkj0iHAk99WTM34hrYi8w8T7KTrnuZAlQ_JcAuU9B3YyTB2StCoCb4RjVjc1qIsacXA.png">(view full size)</a> |







Commit 5a588339dc52f777918fe5ec22f1cc4f5c96a7f7 (https://www-1p9yfye7j-my-covid-story.vercel.app).

2021-05-29 18:38 UTC, davesteinberg requested changes
I have to question most of the FAQ edits. Much of the original language was specifically about the leadership of the response in Ontario, and it's inaccurate to generalize that to the whole country. e.g. significant portions of the country were never in a humanitarian crisis, leadership across the country has ranged from excellent (in Atlantic Canada) to mixed (Quebec and BC) to disastrous (Ontario, Manitoba, and Alberta). And some of the original language might not even apply to Ontario anymore (I don't think we're being led _into_ a humanitarian crisis anymore).

I think we should get some input from the comms folks before updating this content.

2021-05-29 18:48 UTC, davesteinberg commented on pages/about.tsx
> +            We are a group of concerned Candians who can no longer stand by as our country is led
Missing an a in Canadians.

2021-06-03 13:27 UTC, davesteinberg commented
The new copy is here: https://docs.google.com/document/d/1KA-oULnf45t5SL8dBhj8D2IJWmEE1oIR4C-ARyZlYZY/edit?usp=sharing

Also, Natasha highlighted the request from Kapil to remove his name from the list on the About page by the end of this week. Is that doable for you, @silent1mezzo?

2021-06-07 01:04 UTC, closed without merging